### ISSUE TITLE
Monolog\LogRecord

### ISSUE THREAD

**Issue by flexgrip** [marickvantuil/laravel-google-cloud-logging#3]
Hey there,

Just tried installing this package. Laravel 9 and 10. Then deploying to GAE standard php runtimes.

Noticed that it didn't work, and the first thing in the logs is:

`PHP Fatal error:  Declaration of Marick\LaravelGoogleCloudLogging\Handler::isHandling(Monolog\LogRecord $record): bool must be compatible with Monolog\Handler\HandlerInterface::isHandling(array $record): bool in /workspace/vendor/marick/laravel-google-cloud-logging/src/Handler.php on line 20`

I don't quite understand monolog well enough to know whats going on. I could try forking this and changing isHandling to expect an array instead of the LogRecord interface.

What do you think? I actually don't know if this package would even help me. When I have my GAE apps use the errorlog driver, I get the scattered truncated bad logs we are all used to in Google Cloud. Was hoping maybe this would clean them up?

Either way, I am really appreciative of your work! Thanks!

**Comment by marickvantuil** [comment]
Hey, I think this happens because Laravel 9.x uses Monolog 2.x. This package currently only supports Laravel 10 and 11. I hope this helps?
